# Generated by Django 5.0.7 on 2024-08-10 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmirecord',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='savedexercise',
            name='date_executed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
